# Generated by Django 5.2.6 on 2025-09-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='scanner_device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scanner_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='scanner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
